//alert("Hola mundo");
//const nombre =prompt('ingrese nombre');
//document.queryselector('.contenido').innetHTML=`${nombre} esta trabajando con java`
console.log("Hola mundo desde consola")
let numero1 =prompt('ingrese el un valor nuemerico')
let numero2 =prompt('ingrese numero 2')
console.log(numero1);
console.log(numero2);
//suma de valores desde la consola
console.log("la suma de los valores es:"+ (parseInt(numero1)+parseInt(numero2)));